apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: ClusterOriginIssuer
metadata:
  name: prod-issuer
spec:
  requestType: OriginECC
  auth:
    tokenRef:
      name: cloudflare-api-key
      key: apiKey
