apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: r2-backup
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: r2-backup
    creationPolicy: Owner
  data:
    - secretKey: accessKeyId
      remoteRef:
        key: {{ required "cluster is required" .Values.cluster }}-cloudflare-postgres_backup/username
    - secretKey: secretAccessKey
      remoteRef:
        key: {{ .Values.cluster }}-cloudflare-postgres_backup/credential
